### PR TITLE
gateway: use pod ip as cluster host

### PR DESCRIPTION
**Pull request by deepthidevaki**
Use pod ip for ZEEBE_GATEWAY_CLUSTER_HOST. This way broker can send messages to this ip to communicate to this gateway.

### CODE REVIEW

**Comment by salaboy** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **zelldon**

If they are not already assigned, you can assign the PR to them by writing `/assign @zelldon` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=zeebe-io%2Fzeebe-cluster-helm).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/zeebe-io/zeebe-cluster-helm/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by deepthidevaki** [comment]
@salaboy Let me know if there is a better way to do it. What we need is unique address by which broker can communicate to the gateway. If there are multiple gateways, each of them should have different address.

**Comment by 0x15e** [comment]
When can we expect an approval / merge for this PR? Without it, Zeebe 0.23.x is completely unusable in k8s due to extremely long delays between service tasks that use long-polling workers (as in, multiple second long delays).

**Comment by salaboy** [comment]
@0x15e merged.. I will test it and probably release it tomorrow.

**Pull request merged**
