### PR TITLE
Update to 0.25.0

### PR DESCRIPTION
**Pull request by salaboy**
@npepinpe @Zelldon any objections to upgrade the version here?

### CODE REVIEW

**Comment by salaboy** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **salaboy**
You can assign the PR to them by writing `/assign @salaboy` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=zeebe-io%2Fzeebe-cluster-helm).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/zeebe-io/zeebe-cluster-helm/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by npepinpe** [comment]
How do you want to communicate to users the upgrade process? It's possible they run into issues blindly upgrading the Helm chart and going from 0.24.x to 0.25.0.

**Comment by salaboy** [comment]
@npepinpe so if we merge the docs section I can link that into the helm.zeebe.io page. But I don't think that this is a problem for us alone. If you do an upgrade of ElasticSearch helm chart with existing data, I don't know that the charts or even ElasticSearch is doing an upgrade between different versions that is safe. 
As being a community effort, we can mention in the helm.zeebe.io page that users can upgrade to newest versions of the charts, but they need to back up their data, as we are not responsible for any loss.

**Comment by npepinpe** [comment]
> As being a community effort, we can mention in the helm.zeebe.io page that users can upgrade to newest versions of the charts, but they need to back up their data, as we are not responsible for any loss.

Sounds acceptable to me :+1:

**Review by Zelldon — APPROVED** [review]

**Comment by salaboy** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[Zelldon](https://github.com/zeebe-io/zeebe-cluster-helm/pull/98#pullrequestreview-520733462 "Approved")*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=zeebe-io%2Fzeebe-cluster-helm).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/zeebe-io/zeebe-cluster-helm/blob/master/OWNERS)~~ [Zelldon]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
