### PR TITLE
Updates Zeebe version to 0.24.1 in preparation for release

### PR DESCRIPTION
**Pull request by npepinpe**
This PR prepares the Helm chart for the upcoming 0.24.1 release.

### CODE REVIEW

**Comment by salaboy** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **npepinpe**
You can assign the PR to them by writing `/assign @npepinpe` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=zeebe-io%2Fzeebe-cluster-helm).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](zeebe-io/zeebe-cluster-helm/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by npepinpe** [comment]
Please hold and do not merge until the release is ready to be announced :+1:

**Comment by npepinpe** [comment]
Can now be merged :+1:

**Comment by salaboy** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/zeebe-io/zeebe-cluster-helm/pull/87#pullrequestreview-455395640" title="Approved">Zelldon</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=zeebe-io%2Fzeebe-cluster-helm).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](zeebe-io/zeebe-cluster-helm/blob/master/OWNERS)~~ [Zelldon]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
