### PR TITLE
only deploy ServiceMonitor if prometheusOperator is enabled

### LINKED ISSUE #21: `ServiceMonitor` is not optional
Hey Folks,

first of all - many thanks for the work and effort you put in `zeebe`.  
This piece of software is performing really well in our environment.

I've noticed, that there is a new `manifest` called `service-monitor.yaml` which requires the deployment of an additional operator and the corresponding `CRD`s.

In our case, that specific manifest prohibits a deployment of the latest `zeebe-cluster`-chart.  
Even though the `prometheus-operator` of `CoreOS` is a pretty great solution, we should make  the templating of it's `ServiceMonitor` optional for this `zeebe-cluster`-chart.  

What do you think of adding a simple `if` around here...

```yaml
{{- if .Values.prometheusOperator.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: zeebe-monitor
  labels:
      release: metrics
spec:
  selector:
    matchLabels:
      app: zeebe
  endpoints:
      - honorLabels: true
        port: http
        interval: 10s
{{- end }}
```

### PR DESCRIPTION
**Pull request by Hermsi1337**
Closes #21

### CODE REVIEW

**Comment by salaboy** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **salaboy**

If they are not already assigned, you can assign the PR to them by writing `/assign @salaboy` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=zeebe-io%2Fzeebe-cluster-helm).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/zeebe-io/zeebe-cluster-helm/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by salaboy** [comment]
Hi @Hermsi1337. Thanks for your PR.

I'm waiting for a [zeebe-io](https://github.com/orgs/zeebe-io/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/zeebe-io/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=zeebe-io%2Fzeebe-cluster-helm).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by Zelldon** [comment]
Please don't do it that way. I understand the use case but i would then think that it makes more sense to introduce an extra flag for that. We have the operator installed in one namespace and want to have only the service monitor installed by the helm charts.

Greets Chris

**Comment by salaboy** [comment]
@Zelldon ok.. so what you suggest is to add an unrelated flag.. right? I mean.. something like `prometheus.servicemonitor.enabled` instead of linking it back to the operator itself. I think that makes sense.. and it solves both use cases. @Hermsi1337 can you please adjust as needed?

**Comment by Zelldon** [comment]
Exactly👍

**Comment by Hermsi1337** [comment]
Good catch, Sir.

**Comment by Hermsi1337** [comment]
I've made the changes you two suggested. As default value for `prometheus.servicemonitor.enabled` I've chosen `false` since for me a `helm` chart should not required third party `CRD`s when deploying, but I'm open to discussion.

Since my linter cried badly when I opened the `README.md`, I also did some formatting changes to it.

**Comment by salaboy** [comment]
@Hermsi1337 I am happy with the changes... 
@Zelldon are you ok with setting the new flag to true for your deployments? I believe that `false` is a good default

**Comment by Zelldon** [comment]
Yes thanks👍

**Pull request merged**
